### ISSUE TITLE
Problems to set up sass+compass sprite generator

### ISSUE THREAD

**Issue by rafaelcardoso** [krakenjs/kraken-devtools#20]
Hi Guys.
I'm a little bit confused about how to configure sass and compass sprite generator with the kraken-devtools.

Somebody has already built a setup like this?
I searched on Google but found nothing :/

Thanks.

**Comment by pvenkatakrishnan** [comment]
Did this get solved. Closing it out since it has been open for a while. Please reopen if not solved yet.
