### ISSUE TITLE
Add browserify support

### ISSUE THREAD

**Issue by marceloampuerop6** [krakenjs/kraken-devtools#21]
Generator allows you to choose browserify as javascript library.  It works perfect in production mode after grunt build but doesn't work on development.  I'm aware of #19 but it seemed there's no progress since June 4th. Thanks.

**Comment by pvenkatakrishnan** [comment]
This is awesome. Thanks @iantocristian . I can add this module for reference into Readme and close this issue out.

**Comment by pvenkatakrishnan** [comment]
with https://github.com/krakenjs/kraken-devtools/pull/36 closing this.
