### ISSUE TITLE
Asking for precompiled DUST template that doesn't exist crashes the process

### ISSUE THREAD

**Issue by vaughan99** [krakenjs/kraken-devtools#28]
I have a bug in my single page app that yielded a request for a template that doesn't exist.  Rather than returning 404, the devtools middleware crashes when trying to compile the non-existent template.

REQUEST:
https://localhost.paypal.com:7443/developer/templates/US/fr/partials/page/foo.js

CONSOLE:
GET /developer/templates/US/fr/partials/page/foo.properties 404 244.000 ms - 1077954
Wed, 24 Sep 2014 15:19:37 GMT uncaughtException ENOENT, open '/Users/cvaughan/workspace/git/cvaughan/developernodeweb/public/templates/partials/page/foo.dust'
Error: ENOENT, open '/Users/cvaughan/workspace/git/cvaughan/developernodeweb/public/templates/partials/page/foo.dust'

-Chris Vaughan

**Comment by pvenkatakrishnan** [comment]
https://github.com/krakenjs/kraken-devtools/pull/29 this will throw an error causing 404.

**Comment by pvenkatakrishnan** [comment]
closing this as #29 is merged
