### ISSUE TITLE
"pointer being freed was not allocated" with Sass

### ISSUE THREAD

**Issue by ygrenzinger** [krakenjs/kraken-devtools#33]
Hello,

I  really don't understand what's happened (updated some npm packages) but I keep having this error "pointer being freed was not allocated" until I go back to node-neat 0.8.6

What's weird is the patch that @aredridel has done here https://github.com/krakenjs/kraken-devtools/pull/22 was working fine with node-neat 0.9.3

I have tried to make different combination without success. @pvenkatakrishnan seems to have the same problem https://github.com/krakenjs/kraken-devtools/commit/93ae39436a6f6cf991c9c20f4548bfed408cd143

I am not enough skilled to debug node C++ and I need 0.9.3 so I must deactivate kraken-devtools :(

Is there some tips to debug this sort of error and help ?

**Comment by pvenkatakrishnan** [comment]
Looks like between `node-sass` 0.8 and 0.9, `libsass` upgrade has happened. Possibly interfaces have changed and hence.

**Comment by ygrenzinger** [comment]
Great job :+1:  It works even with node-sass 1.2.3
