### ISSUE TITLE
Support Stylus plugins.

### ISSUE THREAD

**Issue by jasisk** [krakenjs/kraken-devtools#45]
As per [this issue on the kraken repo](https://github.com/krakenjs/kraken-js/issues/338), we should add plugin support to the stylus ... plugin.

Basically [this](https://github.com/jasisk/stylus-example/blob/d3d7b5529829eb76ad65320794f39516b2a04b85/lib/stylus.js), but with first class configuration.

**Comment by grawk** [comment]
This appears to be a candidate for an external plugin. Can we create such a repo and close this issue?

**Comment by jasisk** [comment]
Stylus plugins are plugins for Stylus—which we currently house internally. This issue will be carried over when the Stylus plugin gets plucked out.

**Comment by grawk** [comment]
Oh ha. look it's right there!

**Comment by grawk** [comment]
This issue is fixed with the release of `construx@v1.0.0` and `construx-stylus@v1.0.0`. Resolve by upgrading from `kraken-devtools` to `construx` and appropriate plugins.

Please see:
* https://github.com/krakenjs/construx
* https://github.com/krakenjs/construx-stylus
