### ISSUE TITLE
Less Parser constructor not receiving second argument from Kraken-Devtools

### ISSUE THREAD

**Issue by snowinferno** [krakenjs/kraken-devtools#65]
As soon as I reference a less css file in my development environment I get the following error.
I have traced it down as best I can and it appears to be in the way the Less Parser is instantiated.

I've tried replacing my less `@import` with regular css as well as saving the .less file as an empty file.
The error persists as long as it is trying to process the .less file.

Using node@0.10.40, npm@3.4.0, kraken-devtools@1.4.0, less@2.5.3

---

#### The issue itself
In less@2.5.3 lib/less/parser/parser.js#117 it expects the `imports` variable to be an object with a `contents` property. In this case, kraken-devtools@1.4.0 plugins/less.js#37 doesn't supply an `imports` argument to the Parser constructor, thus `imports` is undefined and Parser.parse attempts to access `imports.contents` without checking that it exists.

---

#### Problem locations in projects
Problem area in kraken-devtools: https://github.com/krakenjs/kraken-devtools/blob/master/plugins/less.js#L37
Problem area in less: https://github.com/less/less.js/blob/master/lib/less/parser/parser.js#L117

---

#### Error
```javascript
TypeError: Cannot read property 'contents' of undefined
    at Object.Parser.parse (/ProjectRoot/node_modules/less/lib/less/parser/parser.js:117:20)
    at module.exports (/ProjectRoot/node_modules/kraken-devtools/plugins/less.js:37:20)
    at /ProjectRoot/node_modules/kraken-devtools/lib/middleware.js:154:9
    at asyncWrap (/ProjectRoot/node_modules/async-listener/glue.js:188:31)
    at fs.js:272:14
    at fs.gracefulify (/ProjectRoot/node_modules/graceful-fs/graceful-fs.js:42:10)
    at originalCloseSync (/ProjectRoot/node_modules/module-config-paypal/node_modules/graceful-fs/graceful-fs.js:104:5)
    at asyncWrap (/ProjectRoot/node_modules/async-listener/glue.js:188:31)
    at Object.oncomplete (fs.js:108:15)
```

**Comment by grawk** [comment]
You should be able to replace the less devtools compiler with the newer `construx-less` compiler. We've got the `construx*` modules now, in order to better maintain different compilers (less, sass, etc) and versions of those as they become available. More info here:
https://github.com/krakenjs/construx

You don't have to replace all your devtools compilers at once. You can start with `construx-less` and see if it solves this problem. It does use a different API into the less compiler so I think it should work.

**Comment by snowinferno** [comment]
That does resolve the problem.

Is construx the new preferred method going forward for on-the-fly compiling in dev environments?

Thanks!

**Comment by grawk** [comment]
Yes, construx is the preferred hot loading solution going forward. Since devtools has all technology plugins bundled within, it became a maintenance nightmare to keep everyone supported based on the different versions of 3rd party technology..
